env:
  browser: true
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-explicit-any": off
  "react/react-in-jsx-scope": off
